<?php

namespace Peerassess\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkingSchemeSectionGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkingSchemeSectionGradeRepository extends EntityRepository
{
}
